version: '3.9'

services:
    nginx:
        image: nginx
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        volumes:
            - wp:/var/www/html
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress
    wordpress:
        image: wordpress
        build:
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        container_name: wordpress
        restart: always
        volumes:
            - wp:/var/www/html
        networks:
            - inception
        depends_on: 
            - mariadb
        expose:
            - "9000"
        env_file: .env
    mariadb:
        image: mariadb
        build:
            context: ./requirements/mariadb/
            dockerfile: Dockerfile
        container_name: mariadb
        restart: always
        volumes:
            - db:/var/lib/mysql
        networks:
            - inception
        expose:
            - "3306"
        env_file: .env

networks:
    inception:
        name: inception
        driver: bridge
volumes:
    wp:
        driver: local
        name: wp
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/wordpress
    db:
        driver: local
        name: db
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/mariadb
